<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared.Infrastructure\Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Integration.Contracts\Integration.Contracts.csproj" />
  </ItemGroup>

</Project>
